name: Bug report
description: Is something not exactly right? or just completely broken? then it goes here!
labels: [FIX IT FIX IT FIX IT, Pending Review]
assignees:
  - CharGoldenYT
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs (if existing)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your target?"
      options:
        - "Windows (Via PyInstaller's produced exe)"
        - "Native Python (Via krillyou.py)"
        - "Pre 3.0 | Windows (Via PyInstaller's produced krillyou.exe)"
        - "Pre 3.0 | Native Python (Via krillyou.py)"
    validations:
      required: true

  - type: dropdown
    id: ptarget
    attributes:
      label: "What is your python version (If running native)?"
      options:
        - 3.12.4
        - 3.12.5
        - 3.12.6
        - 3.12.7
        - Other (Specify Below, if above 3.12, may be rejected!)
    validations:
      required: false

  - type: textarea
    id: version
    attributes:
      label: "If other, what version"
    validations:
      required: false

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything? If so, mention or summarize your changes."
      placeholder: "Yes, I edited your mom."
    validations:
      required: true
