name: Bug report
description: Is something not exactly right? or just completely broken? then it goes here!
labels: [FIX IT FIX IT FIX IT, Pending Review]
assignees:
  - CharGoldenYT
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs (if existing)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your target?"
      options:
        - Discord Bot
        - "Windows (Via PyInstaller's produced exe)"
        - "Native Python (Via krillyou.py)"
        - "Pre 3.0 | Windows (Via PyInstaller's produced krillyou.exe)"
        - "Pre 3.0 | Native Python (Via krillyou.py)"
    validations:
      required: true

  - type: dropdown
    id: ptarget
    attributes:
      label: "(Sight Test) What is your python version (If running native)?"
      options:
        - 3.8.x
        - 3.9.x
        - 3.10.x
        - 3.11.x
        - 3.12.x
        - 3.13.x
    validations:
      required: false

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything? If so, mention or summarize your changes."
      placeholder: "PUT CHEMICALS IN THE WATER THAT TURN THE FRIGGIN FROGS GAY"
    validations:
      required: true
