name: Documentation Suggestion
description: Got an idea to better the documentation? Report it here!
title: "Documentation Suggestion: "
labels: [Documentation Suggestion, Pending Review]
assignees:
  - CharGoldenYT
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your suggestion here."
    validations:
      required: true
