name: Help Me!
description: Are you confused about something? refer [here](https://github.com/CharGoldenYT/KrillYouBot/issues/4) for what NOT to request
labels: [HELP ME. HELP. ME., Pending Review]
assignees:
  - CharGoldenYT
body:
  - type: textarea
    id: description
    attributes:
      label: "What do you need help with?"
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your target?"
      options:
        - "Windows (Via PyInstaller's produced krillyou.exe)"
        - "Native Python (Via krillyou.py)"
    validations:
      required: true

  - type: dropdown
    id: sighttest
    attributes:
      label: "(Sight Test) What shouldn't you request?"
      options:
        - "A nice flower."
        - "Fixing your damn documentation, its stupid."
        - "Make the server settings an embed."
    validations:
      required: true
