name: Issue Template Suggestion
description: Got an idea to better the Issue Templates? Report it here!
title: "Documentation Suggestion: "
labels: [Issue Suggestion, Pending Review, Suggestion]
assignees:
  - CharGoldenYT
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your suggestion here."
    validations:
      required: true
